language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t cloud119/docker-react -f Dockerfile.dev . 


script:
  - docker run -e CI=true cloud119/docker-react npm run test -- --coverage

